---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-app-dep
  labels:
    app: consumer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-app
  template:
    metadata:
      labels:
        app: consumer-app
    spec:
      containers:
        - name: consumer-app
          image: arturix/consumersb:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-app-ext-svc
spec:
  selector:
    app: consumer-app
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
      protocol: TCP
